### ISSUE TITLE
Remove API key from public repository

### ISSUE THREAD

**Issue by nathanv** [IYCI/MyClass#46]
Hello Jason,
Thank you for your contributions to the uWaterloo app scene.
An issue we've noticed with your app: You have your private key posted as source here on github:
see: https://github.com/IYCI/MyClass/blob/8eb98ac2f2922e6cb89b9e267cec8a4999881bcb/app/src/main/java/com/YC2010/MyClass/utils/Constants.java#L14

Please remove and use a place-holder. See http://stackoverflow.com/questions/14570989/best-practice-for-storing-private-api-keys-in-android for best practice information.

Warm Regards,
Nate

Nathan Vexler
Open Data Service Lead
Client Services, Information Systems & Technology
University of Waterloo
EC2 - 2nd floor / Main Campus / Waterloo, Ontario
https://uwaterloo.ca/open-data

**Comment by IYCI** [comment]
Thank you! We will look into it and update the app ASAP.

**Comment by nathanv** [comment]
Great @IYCI ! Thank you for acting so quickly on this.
